/*
** Copyright 2012 Double Precision, Inc.
** See COPYING for distribution information.
*/

#ifndef repoclusterinfoimplfwd_H
#define repoclusterinfoimplfwd_H

#include <x/ref.H>
#include <x/ptr.H>

class repoclusterinfoimplObj;

//! A reference to a repoclusterinfoimplObj;
typedef x::ref<repoclusterinfoimplObj> repoclusterinfoimpl;

//! A nullable pointer reference to a repoclusterinfoimplObj;
typedef x::ptr<repoclusterinfoimplObj> repoclusterinfoimplptr;

#endif
